---
name: VideoLan-Client
version: 0.1
author:
  - 'Cyrille Hombecq <cyrille.hombecq@gmail.com>'
abstract: interact with VideoLan Client using telnet connection
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  VideoLan::Client:
    file: lib/VideoLan/Client.pm
    version: 0.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
