---
name: VideoLan-Client
version: 0.11
author:
  - 'Cyrille Hombecq <cyrille.hombecq@gmail.com>'
abstract: interact with VideoLan Client using telnet connection
license: perl
build_requires:
  Net::Telnet: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  VideoLan::Client:
    file: lib/VideoLan/Client.pm
    version: 0.11
resources:
  license: http://dev.perl.org/licenses/
